import type { RoleplayModelProfile } from "./types"

export const euryaleRpProfile: RoleplayModelProfile = {
  id: "euryale-rp",
  provider: "openrouter",
  modelName: process.env.OPENROUTER_UNSHAPED_MODEL || "sao10k/l3.1-euryale-70b",
  temperature: 0.72,
  topP: 0.9,
  maxOutputTokens: 1200,
  promptStyle: "unfiltered-novel",
  outputMode: "novel",
  targetChars: { min: 320, max: 700 },
  maxDialogues: 3,
  validationSensitivity: {
    brokenDialogueQuotes: "repairable",
    tooManyDialogues: "repairable",
    overPhysical: "hard",
    metaLeak: "hard",
    internalTokenLeak: "hard",
    foreignScriptLeak: "hard",
    unpromptedHandFocus: "repairable",
    objectiveUserStateAssertion: "hard",
    userControlByNarration: "hard",
    controlsUser: "hard",
    contractClosureBias: "repairable",
    futureClosure: "repairable",
    responseMissedUserIntent: "repairable",
    lowContentDensity: "repairable",
    excessiveAbstractMood: "repairable",
    characterVoiceWeak: "repairable",
    tooLong: "soft",
  },
  repair: {
    maxAttempts: 1,
    acceptRepairableAfterAttempt: true,
  },
  fallback: {
    providerOrder: ["same", "local"],
    allowLocalFallback: false,
  },
}
