import type { RoleplayModelProfile } from "./types"
import { DEFAULT_MAX_ANSWER_CHARS, DEFAULT_MIN_ANSWER_CHARS } from "@/lib/chat-models"

export const openaiRpProfile: RoleplayModelProfile = {
  id: "openai-rp",
  provider: "openai",
  modelName: process.env.OPENAI_CHAT_MODEL || "gpt-4o-mini",
  temperature: 0.75,
  topP: 0.9,
  maxOutputTokens: 4000,
  promptStyle: "concise-direct",
  outputMode: "chat",
  targetChars: { min: DEFAULT_MIN_ANSWER_CHARS, max: DEFAULT_MAX_ANSWER_CHARS },
  minDialogues: 2,
  preferredDialogues: 3,
  maxDialogues: 4,
  validationSensitivity: {
    brokenDialogueQuotes: "repairable",
    tooFewDialogues: "repairable",
    tooManyDialogues: "repairable",
    overPhysical: "hard",
    metaLeak: "hard",
    internalTokenLeak: "hard",
    foreignScriptLeak: "hard",
    unpromptedHandFocus: "repairable",
    objectiveUserStateAssertion: "hard",
    userControlByNarration: "hard",
    controlsUser: "hard",
    contractClosureBias: "repairable",
    futureClosure: "repairable",
    responseMissedUserIntent: "repairable",
    lowContentDensity: "repairable",
    excessiveAbstractMood: "repairable",
    characterVoiceWeak: "repairable",
    tooShort: "soft",
    tooLong: "repairable",
    // 재시도 시 유사 답변 생성 방지 - 너무 엄격하면 루프 발생하므로 soft 처리
    previousResponseDuplicate: "soft",
    regenerationDuplicate: "soft",
    incompleteEnding: "repairable",
  },
  repair: {
    maxAttempts: 1,
    acceptRepairableAfterAttempt: true,
  },
  fallback: {
    providerOrder: ["same", "local"],
    allowLocalFallback: false,
  },
}
